[package]
name = "http4r-example-app"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http4r-core = "0.0.0" # import from crate.io rather than locally
