[package]
name = "http4r-example-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http4r-core = { path = "../http4r-core" }
