#!/usr/bin/env bash

set -x

echo "******** build and test *********"
cargo test

pushd http4r-core
cargo doc --no-deps --target-dir doc
popd


echo "******** building WASM *********"
pushd http4r-browser
wasm-pack --verbose build --target web
popd

#echo "********* docs website **********"
#heroku buildpacks:set emk/rust